name: GitHub Actions Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            ./client/package-lock.json
            ./functions/package-lock.json

      - name: Cache Client Dependencies
        uses: actions/cache@v3
        with:
          path: ./client/node_modules
          key: client-${{ runner.os }}-node-${{ hashFiles('./client/package-lock.json') }}

      - name: Install dependencies for Client
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run build

      - name: Cache Functions Dependencies
        uses: actions/cache@v3
        with:
          path: ./functions/node_modules
          key: functions-${{ runner.os }}-node-${{ hashFiles('./functions/package-lock.json') }}

      - name: Install dependencies for Functions
        working-directory: ./functions
        run: npm install

      - name: Build Functions
        working-directory: ./functions
        run: npm run build

  test:
    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            ./client/package-lock.json
            ./functions/package-lock.json

      - name: Cache Client Dependencies
        uses: actions/cache@v3
        with:
          path: ./client/node_modules
          key: client-${{ runner.os }}-node-${{ hashFiles('./client/package-lock.json') }}

      - name: Install dependencies for Client
        working-directory: ./client
        run: npm install

      - name: Run Client tests
        working-directory: ./client
        run: npm run test -- --coverage
